"""Constants for PRCustomComponent tests."""
from custom_components.pr_custom_component.const import CONF_PR_URL

# Mock config data to be used across multiple tests
TEST_PR_URL = "https://github.com/home-assistant/core/pull/46558"
TEST_API_PR_URL = "https://api.github.com/repos/home-assistant/core/pulls/46558"
TEST_API_DATA_URL = "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla?ref=tesla_oauth_callback"
TEST_INIT_URL = "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/__init__.py?ref=tesla_oauth_callback"
TEST_TRANSLATIONS_URL = "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/translations?ref=tesla_oauth_callback"
MOCK_CONFIG = {CONF_PR_URL: TEST_PR_URL}
MOCK_CONFIG_DATA = {
    "pr_url": TEST_PR_URL,
    "name": "tesla",
    "update_time": "2021-03-14T03:54:43Z",
    "pull_number": 46558,
}
TEST_CONFIG_PATH = "/config"

MOCK_PR_RESPONSE = {
    "url": "https://api.github.com/repos/home-assistant/core/pulls/46558",
    "id": 573327933,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NTczMzI3OTMz",
    "html_url": "https://github.com/home-assistant/core/pull/46558",
    "diff_url": "https://github.com/home-assistant/core/pull/46558.diff",
    "patch_url": "https://github.com/home-assistant/core/pull/46558.patch",
    "issue_url": "https://api.github.com/repos/home-assistant/core/issues/46558",
    "number": 46558,
    "state": "open",
    "locked": False,
    "title": "WIP: Add oauth proxy login for Tesla",
    "user": {
        "login": "alandtse",
        "id": 7086117,
        "node_id": "MDQ6VXNlcjcwODYxMTc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7086117?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/alandtse",
        "html_url": "https://github.com/alandtse",
        "followers_url": "https://api.github.com/users/alandtse/followers",
        "following_url": "https://api.github.com/users/alandtse/following{/other_user}",
        "gists_url": "https://api.github.com/users/alandtse/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/alandtse/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alandtse/subscriptions",
        "organizations_url": "https://api.github.com/users/alandtse/orgs",
        "repos_url": "https://api.github.com/users/alandtse/repos",
        "events_url": "https://api.github.com/users/alandtse/events{/privacy}",
        "received_events_url": "https://api.github.com/users/alandtse/received_events",
        "type": "User",
        "site_admin": False,
    },
    "body": "<!--\r\n  You are amazing! Thanks for contributing to our project!\r\n  Please, DO NOT DELETE ANY TEXT from this template! (unless instructed).\r\n-->\r\n## Breaking change\r\n<!--\r\n  If your PR contains a breaking change for existing users, it is important\r\n  to tell them what breaks, how to make it work again and why we did this.\r\n  This piece of text is published with the release notes, so it helps if you\r\n  write it towards our users, not us.\r\n  Note: Remove this section if this PR is NOT a breaking change.\r\n-->\r\n\r\n\r\n## Proposed change\r\n<!--\r\n  Describe the big picture of your changes here to communicate to the\r\n  maintainers why we should accept this pull request. If it fixes a bug\r\n  or resolves a feature request, be sure to link to that issue in the\r\n  additional information section.\r\n-->\r\nSwitches Tesla login to use an oauth proxy to gather user information instead of screen scraping. This automatically solves the MFA issue identified in #46397 and underlying [library](https://github.com/zabuldon/teslajsonpy/issues/118).\r\n\r\n## Type of change\r\n<!--\r\n  What type of change does your PR introduce to Home Assistant?\r\n  NOTE: Please, check only 1! box!\r\n  If your PR requires multiple boxes to be checked, you'll most likely need to\r\n  split it into multiple PRs. This makes things easier and faster to code review.\r\n-->\r\n\r\n- [ ] Dependency upgrade\r\n- [ ] Bugfix (non-breaking change which fixes an issue)\r\n- [ ] New integration (thank you!)\r\n- [x] New feature (which adds functionality to an existing integration)\r\n- [ ] Breaking change (fix/feature causing existing functionality to break)\r\n- [ ] Code quality improvements to existing code or addition of tests\r\n\r\n## Example entry for `configuration.yaml`:\r\n<!--\r\n  Supplying a configuration snippet, makes it easier for a maintainer to test\r\n  your PR. Furthermore, for new integrations, it gives an impression of how\r\n  the configuration would look like.\r\n  Note: Remove this section if this PR does not have an example entry.\r\n-->\r\n\r\n```yaml\r\n# Example configuration.yaml\r\n\r\n```\r\n\r\n## Additional information\r\n<!--\r\n  Details are important, and help maintainers processing your PR.\r\n  Please be sure to fill out additional details, if applicable.\r\n-->\r\n\r\n- This PR fixes or closes issue: fixes # 46397\r\n- This PR is related to issue: #46397 \r\n- Link to documentation pull request: \r\n\r\n## Checklist\r\n<!--\r\n  Put an `x` in the boxes that apply. You can also fill these out after\r\n  creating the PR. If you're unsure about any of them, don't hesitate to ask.\r\n  We're here to help! This is simply a reminder of what we are going to look\r\n  for before merging your code.\r\n-->\r\n\r\n- [x] The code change is tested and works locally.\r\n- [x] Local tests pass. **Your PR cannot be merged unless tests pass**\r\n- [ ] There is no commented out code in this PR.\r\n- [x] I have followed the [development checklist][dev-checklist]\r\n- [x] The code has been formatted using Black (`black --fast homeassistant tests`)\r\n- [x] Tests have been added to verify that the new code works.\r\n\r\nIf user exposed functionality or configuration variables are added/changed:\r\n\r\n- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]\r\n\r\nIf the code communicates with devices, web services, or third-party tools:\r\n\r\n- [x] The [manifest file][manifest-docs] has all fields filled out correctly.  \r\n      Updated and included derived files by running: `python3 -m script.hassfest`.\r\n- [x] New or updated dependencies have been added to `requirements_all.txt`.  \r\n      Updated by running `python3 -m script.gen_requirements_all`.\r\n- [ ] Untested files have been added to `.coveragerc`.\r\n\r\nThe integration reached or maintains the following [Integration Quality Scale][quality-scale]:\r\n<!--\r\n  The Integration Quality Scale scores an integration on the code quality\r\n  and user experience. Each level of the quality scale consists of a list\r\n  of requirements. We highly recommend getting your integration scored!\r\n-->\r\n\r\n- [x] No score or internal\r\n- [ ] 🥈 Silver\r\n- [ ] 🥇 Gold\r\n- [ ] 🏆 Platinum\r\n\r\n<!--\r\n  This project is very active and we have a high turnover of pull requests.\r\n\r\n  Unfortunately, the number of incoming pull requests is higher than what our\r\n  reviewers can review and merge so there is a long backlog of pull requests\r\n  waiting for review. You can help here!\r\n  \r\n  By reviewing another pull request, you will help raise the code quality of\r\n  that pull request and the final review will be faster. This way the general\r\n  pace of pull request reviews will go up and your wait time will go down.\r\n  \r\n  When picking a pull request to review, try to choose one that hasn't yet\r\n  been reviewed.\r\n\r\n  Thanks for helping out!\r\n-->\r\n\r\nTo help with the load of incoming pull requests:\r\n\r\n- [ ] I have reviewed two other [open pull requests][prs] in this repository.\r\n\r\n[prs]: https://github.com/home-assistant/core/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3ATrue+-label%3Awaiting-for-upstream+sort%3Acreated-desc+review%3Anone\r\n\r\n<!--\r\n  Thank you for contributing <3\r\n\r\n  Below, some useful links you could explore:\r\n-->\r\n[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html\r\n[manifest-docs]: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html\r\n[quality-scale]: https://developers.home-assistant.io/docs/en/next/integration_quality_scale_index.html\r\n[docs-repository]: https://github.com/home-assistant/home-assistant.io\r\n",
    "created_at": "2021-02-15T07:16:19Z",
    "updated_at": "2021-03-14T03:54:43Z",
    "closed_at": None,
    "merged_at": None,
    "merge_commit_sha": "fd92433343f350d45b3609303220ac9c2d753d61",
    "assignee": None,
    "assignees": [],
    "requested_reviewers": [],
    "requested_teams": [],
    "labels": [
        {
            "id": 1601949504,
            "node_id": "MDU6TGFiZWwxNjAxOTQ5NTA0",
            "url": "https://api.github.com/repos/home-assistant/core/labels/by-code-owner",
            "name": "by-code-owner",
            "color": "ffc1fd",
            "default": False,
            "description": "",
        },
        {
            "id": 527871105,
            "node_id": "MDU6TGFiZWw1Mjc4NzExMDU=",
            "url": "https://api.github.com/repos/home-assistant/core/labels/cla-signed",
            "name": "cla-signed",
            "color": "008000",
            "default": False,
            "description": None,
        },
        {
            "id": 678946932,
            "node_id": "MDU6TGFiZWw2Nzg5NDY5MzI=",
            "url": "https://api.github.com/repos/home-assistant/core/labels/integration:%20tesla",
            "name": "integration: tesla",
            "color": "ededed",
            "default": False,
            "description": None,
        },
        {
            "id": 898370392,
            "node_id": "MDU6TGFiZWw4OTgzNzAzOTI=",
            "url": "https://api.github.com/repos/home-assistant/core/labels/new-feature",
            "name": "new-feature",
            "color": "d4c5f9",
            "default": False,
            "description": "",
        },
    ],
    "milestone": None,
    "draft": True,
    "commits_url": "https://api.github.com/repos/home-assistant/core/pulls/46558/commits",
    "review_comments_url": "https://api.github.com/repos/home-assistant/core/pulls/46558/comments",
    "review_comment_url": "https://api.github.com/repos/home-assistant/core/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/home-assistant/core/issues/46558/comments",
    "statuses_url": "https://api.github.com/repos/home-assistant/core/statuses/10f2c74c49a471d0ba95e2d9f7e1e0a4315276a3",
    "head": {
        "label": "alandtse:tesla_oauth_callback",
        "ref": "tesla_oauth_callback",
        "sha": "10f2c74c49a471d0ba95e2d9f7e1e0a4315276a3",
        "user": {
            "login": "alandtse",
            "id": 7086117,
            "node_id": "MDQ6VXNlcjcwODYxMTc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/7086117?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/alandtse",
            "html_url": "https://github.com/alandtse",
            "followers_url": "https://api.github.com/users/alandtse/followers",
            "following_url": "https://api.github.com/users/alandtse/following{/other_user}",
            "gists_url": "https://api.github.com/users/alandtse/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/alandtse/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/alandtse/subscriptions",
            "organizations_url": "https://api.github.com/users/alandtse/orgs",
            "repos_url": "https://api.github.com/users/alandtse/repos",
            "events_url": "https://api.github.com/users/alandtse/events{/privacy}",
            "received_events_url": "https://api.github.com/users/alandtse/received_events",
            "type": "User",
            "site_admin": False,
        },
        "repo": {
            "id": 89053950,
            "node_id": "MDEwOlJlcG9zaXRvcnk4OTA1Mzk1MA==",
            "name": "home-assistant",
            "full_name": "alandtse/home-assistant",
            "private": False,
            "owner": {
                "login": "alandtse",
                "id": 7086117,
                "node_id": "MDQ6VXNlcjcwODYxMTc=",
                "avatar_url": "https://avatars.githubusercontent.com/u/7086117?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/alandtse",
                "html_url": "https://github.com/alandtse",
                "followers_url": "https://api.github.com/users/alandtse/followers",
                "following_url": "https://api.github.com/users/alandtse/following{/other_user}",
                "gists_url": "https://api.github.com/users/alandtse/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/alandtse/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/alandtse/subscriptions",
                "organizations_url": "https://api.github.com/users/alandtse/orgs",
                "repos_url": "https://api.github.com/users/alandtse/repos",
                "events_url": "https://api.github.com/users/alandtse/events{/privacy}",
                "received_events_url": "https://api.github.com/users/alandtse/received_events",
                "type": "User",
                "site_admin": False,
            },
            "html_url": "https://github.com/alandtse/home-assistant",
            "description": ":house_with_garden: Open-source home automation platform running on Python 3",
            "fork": True,
            "url": "https://api.github.com/repos/alandtse/home-assistant",
            "forks_url": "https://api.github.com/repos/alandtse/home-assistant/forks",
            "keys_url": "https://api.github.com/repos/alandtse/home-assistant/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/alandtse/home-assistant/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/alandtse/home-assistant/teams",
            "hooks_url": "https://api.github.com/repos/alandtse/home-assistant/hooks",
            "issue_events_url": "https://api.github.com/repos/alandtse/home-assistant/issues/events{/number}",
            "events_url": "https://api.github.com/repos/alandtse/home-assistant/events",
            "assignees_url": "https://api.github.com/repos/alandtse/home-assistant/assignees{/user}",
            "branches_url": "https://api.github.com/repos/alandtse/home-assistant/branches{/branch}",
            "tags_url": "https://api.github.com/repos/alandtse/home-assistant/tags",
            "blobs_url": "https://api.github.com/repos/alandtse/home-assistant/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/alandtse/home-assistant/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/alandtse/home-assistant/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/alandtse/home-assistant/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/alandtse/home-assistant/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/alandtse/home-assistant/languages",
            "stargazers_url": "https://api.github.com/repos/alandtse/home-assistant/stargazers",
            "contributors_url": "https://api.github.com/repos/alandtse/home-assistant/contributors",
            "subscribers_url": "https://api.github.com/repos/alandtse/home-assistant/subscribers",
            "subscription_url": "https://api.github.com/repos/alandtse/home-assistant/subscription",
            "commits_url": "https://api.github.com/repos/alandtse/home-assistant/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/alandtse/home-assistant/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/alandtse/home-assistant/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/alandtse/home-assistant/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/alandtse/home-assistant/contents/{+path}",
            "compare_url": "https://api.github.com/repos/alandtse/home-assistant/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/alandtse/home-assistant/merges",
            "archive_url": "https://api.github.com/repos/alandtse/home-assistant/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/alandtse/home-assistant/downloads",
            "issues_url": "https://api.github.com/repos/alandtse/home-assistant/issues{/number}",
            "pulls_url": "https://api.github.com/repos/alandtse/home-assistant/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/alandtse/home-assistant/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/alandtse/home-assistant/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/alandtse/home-assistant/labels{/name}",
            "releases_url": "https://api.github.com/repos/alandtse/home-assistant/releases{/id}",
            "deployments_url": "https://api.github.com/repos/alandtse/home-assistant/deployments",
            "created_at": "2017-04-22T07:59:13Z",
            "updated_at": "2020-01-27T01:54:42Z",
            "pushed_at": "2021-03-19T15:42:20Z",
            "git_url": "git://github.com/alandtse/home-assistant.git",
            "ssh_url": "git@github.com:alandtse/home-assistant.git",
            "clone_url": "https://github.com/alandtse/home-assistant.git",
            "svn_url": "https://github.com/alandtse/home-assistant",
            "homepage": "https://home-assistant.io",
            "size": 226936,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "Python",
            "has_issues": False,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": False,
            "has_pages": False,
            "forks_count": 1,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 4,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI=",
            },
            "forks": 1,
            "open_issues": 4,
            "watchers": 0,
            "default_branch": "dev",
        },
    },
    "base": {
        "label": "home-assistant:dev",
        "ref": "dev",
        "sha": "c53a462b3db6165a9b6ce20acd6c0f5130384bf4",
        "user": {
            "login": "home-assistant",
            "id": 13844975,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzODQ0OTc1",
            "avatar_url": "https://avatars.githubusercontent.com/u/13844975?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/home-assistant",
            "html_url": "https://github.com/home-assistant",
            "followers_url": "https://api.github.com/users/home-assistant/followers",
            "following_url": "https://api.github.com/users/home-assistant/following{/other_user}",
            "gists_url": "https://api.github.com/users/home-assistant/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/home-assistant/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/home-assistant/subscriptions",
            "organizations_url": "https://api.github.com/users/home-assistant/orgs",
            "repos_url": "https://api.github.com/users/home-assistant/repos",
            "events_url": "https://api.github.com/users/home-assistant/events{/privacy}",
            "received_events_url": "https://api.github.com/users/home-assistant/received_events",
            "type": "Organization",
            "site_admin": False,
        },
        "repo": {
            "id": 12888993,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMjg4ODk5Mw==",
            "name": "core",
            "full_name": "home-assistant/core",
            "private": False,
            "owner": {
                "login": "home-assistant",
                "id": 13844975,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzODQ0OTc1",
                "avatar_url": "https://avatars.githubusercontent.com/u/13844975?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/home-assistant",
                "html_url": "https://github.com/home-assistant",
                "followers_url": "https://api.github.com/users/home-assistant/followers",
                "following_url": "https://api.github.com/users/home-assistant/following{/other_user}",
                "gists_url": "https://api.github.com/users/home-assistant/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/home-assistant/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/home-assistant/subscriptions",
                "organizations_url": "https://api.github.com/users/home-assistant/orgs",
                "repos_url": "https://api.github.com/users/home-assistant/repos",
                "events_url": "https://api.github.com/users/home-assistant/events{/privacy}",
                "received_events_url": "https://api.github.com/users/home-assistant/received_events",
                "type": "Organization",
                "site_admin": False,
            },
            "html_url": "https://github.com/home-assistant/core",
            "description": ":house_with_garden: Open source home automation that puts local control and privacy first",
            "fork": False,
            "url": "https://api.github.com/repos/home-assistant/core",
            "forks_url": "https://api.github.com/repos/home-assistant/core/forks",
            "keys_url": "https://api.github.com/repos/home-assistant/core/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/home-assistant/core/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/home-assistant/core/teams",
            "hooks_url": "https://api.github.com/repos/home-assistant/core/hooks",
            "issue_events_url": "https://api.github.com/repos/home-assistant/core/issues/events{/number}",
            "events_url": "https://api.github.com/repos/home-assistant/core/events",
            "assignees_url": "https://api.github.com/repos/home-assistant/core/assignees{/user}",
            "branches_url": "https://api.github.com/repos/home-assistant/core/branches{/branch}",
            "tags_url": "https://api.github.com/repos/home-assistant/core/tags",
            "blobs_url": "https://api.github.com/repos/home-assistant/core/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/home-assistant/core/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/home-assistant/core/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/home-assistant/core/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/home-assistant/core/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/home-assistant/core/languages",
            "stargazers_url": "https://api.github.com/repos/home-assistant/core/stargazers",
            "contributors_url": "https://api.github.com/repos/home-assistant/core/contributors",
            "subscribers_url": "https://api.github.com/repos/home-assistant/core/subscribers",
            "subscription_url": "https://api.github.com/repos/home-assistant/core/subscription",
            "commits_url": "https://api.github.com/repos/home-assistant/core/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/home-assistant/core/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/home-assistant/core/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/home-assistant/core/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/home-assistant/core/contents/{+path}",
            "compare_url": "https://api.github.com/repos/home-assistant/core/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/home-assistant/core/merges",
            "archive_url": "https://api.github.com/repos/home-assistant/core/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/home-assistant/core/downloads",
            "issues_url": "https://api.github.com/repos/home-assistant/core/issues{/number}",
            "pulls_url": "https://api.github.com/repos/home-assistant/core/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/home-assistant/core/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/home-assistant/core/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/home-assistant/core/labels{/name}",
            "releases_url": "https://api.github.com/repos/home-assistant/core/releases{/id}",
            "deployments_url": "https://api.github.com/repos/home-assistant/core/deployments",
            "created_at": "2013-09-17T07:29:48Z",
            "updated_at": "2021-03-20T04:46:20Z",
            "pushed_at": "2021-03-20T03:52:11Z",
            "git_url": "git://github.com/home-assistant/core.git",
            "ssh_url": "git@github.com:home-assistant/core.git",
            "clone_url": "https://github.com/home-assistant/core.git",
            "svn_url": "https://github.com/home-assistant/core",
            "homepage": "https://www.home-assistant.io",
            "size": 229465,
            "stargazers_count": 41023,
            "watchers_count": 41023,
            "language": "Python",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": False,
            "has_pages": False,
            "forks_count": 13526,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 1640,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI=",
            },
            "forks": 13526,
            "open_issues": 1640,
            "watchers": 41023,
            "default_branch": "dev",
        },
    },
    "_links": {
        "self": {
            "href": "https://api.github.com/repos/home-assistant/core/pulls/46558"
        },
        "html": {"href": "https://github.com/home-assistant/core/pull/46558"},
        "issue": {
            "href": "https://api.github.com/repos/home-assistant/core/issues/46558"
        },
        "comments": {
            "href": "https://api.github.com/repos/home-assistant/core/issues/46558/comments"
        },
        "review_comments": {
            "href": "https://api.github.com/repos/home-assistant/core/pulls/46558/comments"
        },
        "review_comment": {
            "href": "https://api.github.com/repos/home-assistant/core/pulls/comments{/number}"
        },
        "commits": {
            "href": "https://api.github.com/repos/home-assistant/core/pulls/46558/commits"
        },
        "statuses": {
            "href": "https://api.github.com/repos/home-assistant/core/statuses/10f2c74c49a471d0ba95e2d9f7e1e0a4315276a3"
        },
    },
    "author_association": "CONTRIBUTOR",
    "auto_merge": None,
    "active_lock_reason": None,
    "merged": False,
    "mergeable": None,
    "rebaseable": None,
    "mergeable_state": "draft",
    "merged_by": None,
    "comments": 17,
    "review_comments": 0,
    "maintainer_can_modify": True,
    "commits": 8,
    "additions": 621,
    "deletions": 281,
    "changed_files": 16,
}

MOCK_DATA_RESPONSE = [
    {
        "name": "__init__.py",
        "path": "homeassistant/components/tesla/__init__.py",
        "sha": "9e6db33d24ab50c1af1e1e2818580cc96069e076",
        "size": 9220,
        "url": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/__init__.py?ref=tesla_oauth_callback",
        "html_url": "https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
        "git_url": "https://api.github.com/repos/alandtse/home-assistant/git/blobs/9e6db33d24ab50c1af1e1e2818580cc96069e076",
        "download_url": "https://raw.githubusercontent.com/alandtse/home-assistant/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
        "type": "file",
        "_links": {
            "self": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/__init__.py?ref=tesla_oauth_callback",
            "git": "https://api.github.com/repos/alandtse/home-assistant/git/blobs/9e6db33d24ab50c1af1e1e2818580cc96069e076",
            "html": "https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
        },
    },
    {
        "name": "translations",
        "path": "homeassistant/components/tesla/translations",
        "sha": "95a705f23dee00d3fcd856bb1b4ca976de9680cc",
        "size": 0,
        "url": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/translations?ref=tesla_oauth_callback",
        "html_url": "https://github.com/alandtse/home-assistant/tree/tesla_oauth_callback/homeassistant/components/tesla/translations",
        "git_url": "https://api.github.com/repos/alandtse/home-assistant/git/trees/95a705f23dee00d3fcd856bb1b4ca976de9680cc",
        "download_url": None,
        "type": "dir",
        "_links": {
            "self": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/translations?ref=tesla_oauth_callback",
            "git": "https://api.github.com/repos/alandtse/home-assistant/git/trees/95a705f23dee00d3fcd856bb1b4ca976de9680cc",
            "html": "https://github.com/alandtse/home-assistant/tree/tesla_oauth_callback/homeassistant/components/tesla/translations",
        },
    },
]

MOCK_INIT_RESPONSE = {
    "name": "__init__.py",
    "path": "homeassistant/components/tesla/__init__.py",
    "sha": "9e6db33d24ab50c1af1e1e2818580cc96069e076",
    "size": 9220,
    "url": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/__init__.py?ref=tesla_oauth_callback",
    "html_url": "https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
    "git_url": "https://api.github.com/repos/alandtse/home-assistant/git/blobs/9e6db33d24ab50c1af1e1e2818580cc96069e076",
    "download_url": "https://raw.githubusercontent.com/alandtse/home-assistant/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
    "type": "file",
    "content": "IiIiU3VwcG9ydCBmb3IgVGVzbGEgY2Fycy4iIiIKaW1wb3J0IGFzeW5jaW8K\nZnJvbSBjb2xsZWN0aW9ucyBpbXBvcnQgZGVmYXVsdGRpY3QKZnJvbSBkYXRl\ndGltZSBpbXBvcnQgdGltZWRlbHRhCmltcG9ydCBsb2dnaW5nCgppbXBvcnQg\nYXN5bmNfdGltZW91dApmcm9tIHRlc2xhanNvbnB5IGltcG9ydCBDb250cm9s\nbGVyIGFzIFRlc2xhQVBJCmZyb20gdGVzbGFqc29ucHkuZXhjZXB0aW9ucyBp\nbXBvcnQgSW5jb21wbGV0ZUNyZWRlbnRpYWxzLCBUZXNsYUV4Y2VwdGlvbgoK\nZnJvbSBob21lYXNzaXN0YW50LmNvbmZpZ19lbnRyaWVzIGltcG9ydCBTT1VS\nQ0VfSU1QT1JULCBDb25maWdFbnRyeQpmcm9tIGhvbWVhc3Npc3RhbnQuY29u\nc3QgaW1wb3J0ICgKICAgIENPTkZfQUNDRVNTX1RPS0VOLAogICAgQ09ORl9Q\nQVNTV09SRCwKICAgIENPTkZfU0NBTl9JTlRFUlZBTCwKICAgIENPTkZfVE9L\nRU4sCiAgICBDT05GX1VTRVJOQU1FLAogICAgSFRUUF9VTkFVVEhPUklaRUQs\nCikKZnJvbSBob21lYXNzaXN0YW50LmNvcmUgaW1wb3J0IEhvbWVBc3Npc3Rh\nbnQsIGNhbGxiYWNrCmZyb20gaG9tZWFzc2lzdGFudC5leGNlcHRpb25zIGlt\ncG9ydCBDb25maWdFbnRyeU5vdFJlYWR5CmZyb20gaG9tZWFzc2lzdGFudC5o\nZWxwZXJzIGltcG9ydCBhaW9odHRwX2NsaWVudApmcm9tIGhvbWVhc3Npc3Rh\nbnQuaGVscGVycy51cGRhdGVfY29vcmRpbmF0b3IgaW1wb3J0IERhdGFVcGRh\ndGVDb29yZGluYXRvciwgVXBkYXRlRmFpbGVkCgpmcm9tIC5jb25maWdfZmxv\ndyBpbXBvcnQgQ2Fubm90Q29ubmVjdCwgSW52YWxpZEF1dGgsIHZhbGlkYXRl\nX2lucHV0CmZyb20gLmNvbnN0IGltcG9ydCAoCiAgICBDT05GX0VYUElSQVRJ\nT04sCiAgICBDT05GX1dBS0VfT05fU1RBUlQsCiAgICBEQVRBX0xJU1RFTkVS\nLAogICAgREVGQVVMVF9TQ0FOX0lOVEVSVkFMLAogICAgREVGQVVMVF9XQUtF\nX09OX1NUQVJULAogICAgRE9NQUlOLAogICAgTUlOX1NDQU5fSU5URVJWQUws\nCiAgICBQTEFURk9STVMsCikKCl9MT0dHRVIgPSBsb2dnaW5nLmdldExvZ2dl\ncihfX25hbWVfXykKCgpAY2FsbGJhY2sKZGVmIF9hc3luY19zYXZlX3Rva2Vu\ncyhoYXNzLCBjb25maWdfZW50cnksIGFjY2Vzc190b2tlbiwgcmVmcmVzaF90\nb2tlbiwgZXhwaXJhdGlvbik6CiAgICBoYXNzLmNvbmZpZ19lbnRyaWVzLmFz\neW5jX3VwZGF0ZV9lbnRyeSgKICAgICAgICBjb25maWdfZW50cnksCiAgICAg\nICAgZGF0YT17CiAgICAgICAgICAgICoqY29uZmlnX2VudHJ5LmRhdGEsCiAg\nICAgICAgICAgIENPTkZfQUNDRVNTX1RPS0VOOiBhY2Nlc3NfdG9rZW4sCiAg\nICAgICAgICAgIENPTkZfVE9LRU46IHJlZnJlc2hfdG9rZW4sCiAgICAgICAg\nICAgIENPTkZfRVhQSVJBVElPTjogZXhwaXJhdGlvbiwKICAgICAgICB9LAog\nICAgKQoKCkBjYWxsYmFjawpkZWYgX2FzeW5jX2NvbmZpZ3VyZWRfZW1haWxz\nKGhhc3MpOgogICAgIiIiUmV0dXJuIGEgc2V0IG9mIGNvbmZpZ3VyZWQgVGVz\nbGEgZW1haWxzLiIiIgogICAgcmV0dXJuIHtlbnRyeS50aXRsZSBmb3IgZW50\ncnkgaW4gaGFzcy5jb25maWdfZW50cmllcy5hc3luY19lbnRyaWVzKERPTUFJ\nTil9CgoKYXN5bmMgZGVmIGFzeW5jX3NldHVwKGhhc3MsIGJhc2VfY29uZmln\nKToKICAgICIiIlNldCB1cCBvZiBUZXNsYSBjb21wb25lbnQuIiIiCgogICAg\nZGVmIF91cGRhdGVfZW50cnkoZW1haWwsIGRhdGE9Tm9uZSwgb3B0aW9ucz1O\nb25lKToKICAgICAgICBkYXRhID0gZGF0YSBvciB7fQogICAgICAgIG9wdGlv\nbnMgPSBvcHRpb25zIG9yIHsKICAgICAgICAgICAgQ09ORl9TQ0FOX0lOVEVS\nVkFMOiBERUZBVUxUX1NDQU5fSU5URVJWQUwsCiAgICAgICAgICAgIENPTkZf\nV0FLRV9PTl9TVEFSVDogREVGQVVMVF9XQUtFX09OX1NUQVJULAogICAgICAg\nIH0KICAgICAgICBmb3IgZW50cnkgaW4gaGFzcy5jb25maWdfZW50cmllcy5h\nc3luY19lbnRyaWVzKERPTUFJTik6CiAgICAgICAgICAgIGlmIGVtYWlsICE9\nIGVudHJ5LnRpdGxlOgogICAgICAgICAgICAgICAgY29udGludWUKICAgICAg\nICAgICAgaGFzcy5jb25maWdfZW50cmllcy5hc3luY191cGRhdGVfZW50cnko\nZW50cnksIGRhdGE9ZGF0YSwgb3B0aW9ucz1vcHRpb25zKQoKICAgIGNvbmZp\nZyA9IGJhc2VfY29uZmlnLmdldChET01BSU4pCiAgICBpZiBub3QgY29uZmln\nOgogICAgICAgIHJldHVybiBUcnVlCiAgICBlbWFpbCA9IGNvbmZpZ1tDT05G\nX1VTRVJOQU1FXQogICAgcGFzc3dvcmQgPSBjb25maWdbQ09ORl9QQVNTV09S\nRF0KICAgIHNjYW5faW50ZXJ2YWwgPSBjb25maWdbQ09ORl9TQ0FOX0lOVEVS\nVkFMXQogICAgaWYgZW1haWwgaW4gX2FzeW5jX2NvbmZpZ3VyZWRfZW1haWxz\nKGhhc3MpOgogICAgICAgIHRyeToKICAgICAgICAgICAgaW5mbyA9IGF3YWl0\nIHZhbGlkYXRlX2lucHV0KGhhc3MsIGNvbmZpZykKICAgICAgICBleGNlcHQg\nKENhbm5vdENvbm5lY3QsIEludmFsaWRBdXRoKToKICAgICAgICAgICAgcmV0\ndXJuIEZhbHNlCiAgICAgICAgX3VwZGF0ZV9lbnRyeSgKICAgICAgICAgICAg\nZW1haWwsCiAgICAgICAgICAgIGRhdGE9ewogICAgICAgICAgICAgICAgQ09O\nRl9BQ0NFU1NfVE9LRU46IGluZm9bQ09ORl9BQ0NFU1NfVE9LRU5dLAogICAg\nICAgICAgICAgICAgQ09ORl9UT0tFTjogaW5mb1tDT05GX1RPS0VOXSwKICAg\nICAgICAgICAgICAgIENPTkZfRVhQSVJBVElPTjogaW5mb1tDT05GX0VYUElS\nQVRJT05dLAogICAgICAgICAgICB9LAogICAgICAgICAgICBvcHRpb25zPXtD\nT05GX1NDQU5fSU5URVJWQUw6IHNjYW5faW50ZXJ2YWx9LAogICAgICAgICkK\nICAgIGVsc2U6CiAgICAgICAgaGFzcy5hc3luY19jcmVhdGVfdGFzaygKICAg\nICAgICAgICAgaGFzcy5jb25maWdfZW50cmllcy5mbG93LmFzeW5jX2luaXQo\nCiAgICAgICAgICAgICAgICBET01BSU4sCiAgICAgICAgICAgICAgICBjb250\nZXh0PXsic291cmNlIjogU09VUkNFX0lNUE9SVH0sCiAgICAgICAgICAgICAg\nICBkYXRhPXtDT05GX1VTRVJOQU1FOiBlbWFpbCwgQ09ORl9QQVNTV09SRDog\ncGFzc3dvcmR9LAogICAgICAgICAgICApCiAgICAgICAgKQogICAgICAgIGhh\nc3MuZGF0YS5zZXRkZWZhdWx0KERPTUFJTiwge30pCiAgICAgICAgaGFzcy5k\nYXRhW0RPTUFJTl1bZW1haWxdID0ge0NPTkZfU0NBTl9JTlRFUlZBTDogc2Nh\nbl9pbnRlcnZhbH0KICAgIHJldHVybiBUcnVlCgoKYXN5bmMgZGVmIGFzeW5j\nX3NldHVwX2VudHJ5KGhhc3MsIGNvbmZpZ19lbnRyeSk6CiAgICAiIiJTZXQg\ndXAgVGVzbGEgYXMgY29uZmlnIGVudHJ5LiIiIgogICAgaGFzcy5kYXRhLnNl\ndGRlZmF1bHQoRE9NQUlOLCB7fSkKICAgIGNvbmZpZyA9IGNvbmZpZ19lbnRy\neS5kYXRhCiAgICBjb3VudCA9IDAKICAgIGlmIGhhc3MuY29uZmlnX2VudHJp\nZXMuYXN5bmNfZW50cmllcyhET01BSU4pOgogICAgICAgIGZvciBlbnRyeSBp\nbiBoYXNzLmNvbmZpZ19lbnRyaWVzLmFzeW5jX2VudHJpZXMoRE9NQUlOKToK\nICAgICAgICAgICAgaWYgZW50cnkudGl0bGUgPT0gY29uZmlnX2VudHJ5LnRp\ndGxlOgogICAgICAgICAgICAgICAgYnJlYWsKICAgICAgICAgICAgY291bnQg\nKz0gMQogICAgaWYgY291bnQgPiAwOgogICAgICAgIHdlYnNlc3Npb24gPSBh\naW9odHRwX2NsaWVudC5hc3luY19jcmVhdGVfY2xpZW50c2Vzc2lvbihoYXNz\nKQogICAgZWxzZToKICAgICAgICB3ZWJzZXNzaW9uID0gYWlvaHR0cF9jbGll\nbnQuYXN5bmNfZ2V0X2NsaWVudHNlc3Npb24oaGFzcykKICAgIGVtYWlsID0g\nY29uZmlnX2VudHJ5LnRpdGxlCiAgICBpZiBlbWFpbCBpbiBoYXNzLmRhdGFb\nRE9NQUlOXSBhbmQgQ09ORl9TQ0FOX0lOVEVSVkFMIGluIGhhc3MuZGF0YVtE\nT01BSU5dW2VtYWlsXToKICAgICAgICBzY2FuX2ludGVydmFsID0gaGFzcy5k\nYXRhW0RPTUFJTl1bZW1haWxdW0NPTkZfU0NBTl9JTlRFUlZBTF0KICAgICAg\nICBoYXNzLmNvbmZpZ19lbnRyaWVzLmFzeW5jX3VwZGF0ZV9lbnRyeSgKICAg\nICAgICAgICAgY29uZmlnX2VudHJ5LCBvcHRpb25zPXtDT05GX1NDQU5fSU5U\nRVJWQUw6IHNjYW5faW50ZXJ2YWx9CiAgICAgICAgKQogICAgICAgIGhhc3Mu\nZGF0YVtET01BSU5dLnBvcChlbWFpbCkKICAgIHRyeToKICAgICAgICBjb250\ncm9sbGVyID0gVGVzbGFBUEkoCiAgICAgICAgICAgIHdlYnNlc3Npb24sCiAg\nICAgICAgICAgIGVtYWlsPWNvbmZpZy5nZXQoQ09ORl9VU0VSTkFNRSksCiAg\nICAgICAgICAgIHBhc3N3b3JkPWNvbmZpZy5nZXQoQ09ORl9QQVNTV09SRCks\nCiAgICAgICAgICAgIHJlZnJlc2hfdG9rZW49Y29uZmlnW0NPTkZfVE9LRU5d\nLAogICAgICAgICAgICBhY2Nlc3NfdG9rZW49Y29uZmlnW0NPTkZfQUNDRVNT\nX1RPS0VOXSwKICAgICAgICAgICAgZXhwaXJhdGlvbj1jb25maWcuZ2V0KENP\nTkZfRVhQSVJBVElPTiwgMCksCiAgICAgICAgICAgIHVwZGF0ZV9pbnRlcnZh\nbD1jb25maWdfZW50cnkub3B0aW9ucy5nZXQoCiAgICAgICAgICAgICAgICBD\nT05GX1NDQU5fSU5URVJWQUwsIERFRkFVTFRfU0NBTl9JTlRFUlZBTAogICAg\nICAgICAgICApLAogICAgICAgICkKICAgICAgICByZXN1bHQgPSBhd2FpdCBj\nb250cm9sbGVyLmNvbm5lY3QoCiAgICAgICAgICAgIHdha2VfaWZfYXNsZWVw\nPWNvbmZpZ19lbnRyeS5vcHRpb25zLmdldCgKICAgICAgICAgICAgICAgIENP\nTkZfV0FLRV9PTl9TVEFSVCwgREVGQVVMVF9XQUtFX09OX1NUQVJUCiAgICAg\nICAgICAgICkKICAgICAgICApCiAgICAgICAgcmVmcmVzaF90b2tlbiA9IHJl\nc3VsdFsicmVmcmVzaF90b2tlbiJdCiAgICAgICAgYWNjZXNzX3Rva2VuID0g\ncmVzdWx0WyJhY2Nlc3NfdG9rZW4iXQogICAgICAgIGV4cGlyYXRpb24gPSBy\nZXN1bHRbImV4cGlyYXRpb24iXQogICAgZXhjZXB0IEluY29tcGxldGVDcmVk\nZW50aWFsczoKICAgICAgICBfYXN5bmNfc3RhcnRfcmVhdXRoKGhhc3MsIGNv\nbmZpZ19lbnRyeSkKICAgICAgICByZXR1cm4gRmFsc2UKICAgIGV4Y2VwdCBU\nZXNsYUV4Y2VwdGlvbiBhcyBleDoKICAgICAgICBpZiBleC5jb2RlID09IEhU\nVFBfVU5BVVRIT1JJWkVEOgogICAgICAgICAgICBfYXN5bmNfc3RhcnRfcmVh\ndXRoKGhhc3MsIGNvbmZpZ19lbnRyeSkKICAgICAgICBfTE9HR0VSLmVycm9y\nKCJVbmFibGUgdG8gY29tbXVuaWNhdGUgd2l0aCBUZXNsYSBBUEk6ICVzIiwg\nZXgubWVzc2FnZSkKICAgICAgICByZXR1cm4gRmFsc2UKICAgIF9hc3luY19z\nYXZlX3Rva2VucyhoYXNzLCBjb25maWdfZW50cnksIGFjY2Vzc190b2tlbiwg\ncmVmcmVzaF90b2tlbiwgZXhwaXJhdGlvbikKICAgIGNvb3JkaW5hdG9yID0g\nVGVzbGFEYXRhVXBkYXRlQ29vcmRpbmF0b3IoCiAgICAgICAgaGFzcywgY29u\nZmlnX2VudHJ5PWNvbmZpZ19lbnRyeSwgY29udHJvbGxlcj1jb250cm9sbGVy\nCiAgICApCiAgICAjIEZldGNoIGluaXRpYWwgZGF0YSBzbyB3ZSBoYXZlIGRh\ndGEgd2hlbiBlbnRpdGllcyBzdWJzY3JpYmUKICAgIGVudHJ5X2RhdGEgPSBo\nYXNzLmRhdGFbRE9NQUlOXVtjb25maWdfZW50cnkuZW50cnlfaWRdID0gewog\nICAgICAgICJjb29yZGluYXRvciI6IGNvb3JkaW5hdG9yLAogICAgICAgICJk\nZXZpY2VzIjogZGVmYXVsdGRpY3QobGlzdCksCiAgICAgICAgREFUQV9MSVNU\nRU5FUjogW2NvbmZpZ19lbnRyeS5hZGRfdXBkYXRlX2xpc3RlbmVyKHVwZGF0\nZV9saXN0ZW5lcildLAogICAgfQogICAgX0xPR0dFUi5kZWJ1ZygiQ29ubmVj\ndGVkIHRvIHRoZSBUZXNsYSBBUEkiKQoKICAgIGF3YWl0IGNvb3JkaW5hdG9y\nLmFzeW5jX3JlZnJlc2goKQogICAgaWYgbm90IGNvb3JkaW5hdG9yLmxhc3Rf\ndXBkYXRlX3N1Y2Nlc3M6CiAgICAgICAgcmFpc2UgQ29uZmlnRW50cnlOb3RS\nZWFkeQoKICAgIGFsbF9kZXZpY2VzID0gY29udHJvbGxlci5nZXRfaG9tZWFz\nc2lzdGFudF9jb21wb25lbnRzKCkKCiAgICBpZiBub3QgYWxsX2RldmljZXM6\nCiAgICAgICAgcmV0dXJuIEZhbHNlCgogICAgZm9yIGRldmljZSBpbiBhbGxf\nZGV2aWNlczoKICAgICAgICBlbnRyeV9kYXRhWyJkZXZpY2VzIl1bZGV2aWNl\nLmhhc3NfdHlwZV0uYXBwZW5kKGRldmljZSkKCiAgICBmb3IgcGxhdGZvcm0g\naW4gUExBVEZPUk1TOgogICAgICAgIF9MT0dHRVIuZGVidWcoIkxvYWRpbmcg\nJXMiLCBwbGF0Zm9ybSkKICAgICAgICBoYXNzLmFzeW5jX2NyZWF0ZV90YXNr\nKAogICAgICAgICAgICBoYXNzLmNvbmZpZ19lbnRyaWVzLmFzeW5jX2Zvcndh\ncmRfZW50cnlfc2V0dXAoY29uZmlnX2VudHJ5LCBwbGF0Zm9ybSkKICAgICAg\nICApCiAgICByZXR1cm4gVHJ1ZQoKCmFzeW5jIGRlZiBhc3luY191bmxvYWRf\nZW50cnkoaGFzcywgY29uZmlnX2VudHJ5KSAtPiBib29sOgogICAgIiIiVW5s\nb2FkIGEgY29uZmlnIGVudHJ5LiIiIgogICAgdW5sb2FkX29rID0gYWxsKAog\nICAgICAgIGF3YWl0IGFzeW5jaW8uZ2F0aGVyKAogICAgICAgICAgICAqWwog\nICAgICAgICAgICAgICAgaGFzcy5jb25maWdfZW50cmllcy5hc3luY19mb3J3\nYXJkX2VudHJ5X3VubG9hZChjb25maWdfZW50cnksIHBsYXRmb3JtKQogICAg\nICAgICAgICAgICAgZm9yIHBsYXRmb3JtIGluIFBMQVRGT1JNUwogICAgICAg\nICAgICBdCiAgICAgICAgKQogICAgKQogICAgZm9yIGxpc3RlbmVyIGluIGhh\nc3MuZGF0YVtET01BSU5dW2NvbmZpZ19lbnRyeS5lbnRyeV9pZF1bREFUQV9M\nSVNURU5FUl06CiAgICAgICAgbGlzdGVuZXIoKQogICAgdXNlcm5hbWUgPSBj\nb25maWdfZW50cnkudGl0bGUKICAgIGlmIHVubG9hZF9vazoKICAgICAgICBo\nYXNzLmRhdGFbRE9NQUlOXS5wb3AoY29uZmlnX2VudHJ5LmVudHJ5X2lkKQog\nICAgICAgIF9MT0dHRVIuZGVidWcoIlVubG9hZGVkIGVudHJ5IGZvciAlcyIs\nIHVzZXJuYW1lKQogICAgICAgIHJldHVybiBUcnVlCiAgICByZXR1cm4gRmFs\nc2UKCgpkZWYgX2FzeW5jX3N0YXJ0X3JlYXV0aChoYXNzOiBIb21lQXNzaXN0\nYW50LCBlbnRyeTogQ29uZmlnRW50cnkpOgogICAgaGFzcy5hc3luY19jcmVh\ndGVfdGFzaygKICAgICAgICBoYXNzLmNvbmZpZ19lbnRyaWVzLmZsb3cuYXN5\nbmNfaW5pdCgKICAgICAgICAgICAgRE9NQUlOLAogICAgICAgICAgICBjb250\nZXh0PXsic291cmNlIjogInJlYXV0aCJ9LAogICAgICAgICAgICBkYXRhPWVu\ndHJ5LmRhdGEsCiAgICAgICAgKQogICAgKQogICAgX0xPR0dFUi5lcnJvcigi\nQ3JlZGVudGlhbHMgYXJlIG5vIGxvbmdlciB2YWxpZC4gUGxlYXNlIHJlYXV0\naGVudGljYXRlIikKCgphc3luYyBkZWYgdXBkYXRlX2xpc3RlbmVyKGhhc3Ms\nIGNvbmZpZ19lbnRyeSk6CiAgICAiIiJVcGRhdGUgd2hlbiBjb25maWdfZW50\ncnkgb3B0aW9ucyB1cGRhdGUuIiIiCiAgICBjb250cm9sbGVyID0gaGFzcy5k\nYXRhW0RPTUFJTl1bY29uZmlnX2VudHJ5LmVudHJ5X2lkXVsiY29vcmRpbmF0\nb3IiXS5jb250cm9sbGVyCiAgICBvbGRfdXBkYXRlX2ludGVydmFsID0gY29u\ndHJvbGxlci51cGRhdGVfaW50ZXJ2YWwKICAgIGNvbnRyb2xsZXIudXBkYXRl\nX2ludGVydmFsID0gY29uZmlnX2VudHJ5Lm9wdGlvbnMuZ2V0KENPTkZfU0NB\nTl9JTlRFUlZBTCkKICAgIGlmIG9sZF91cGRhdGVfaW50ZXJ2YWwgIT0gY29u\ndHJvbGxlci51cGRhdGVfaW50ZXJ2YWw6CiAgICAgICAgX0xPR0dFUi5kZWJ1\nZygKICAgICAgICAgICAgIkNoYW5naW5nIHNjYW5faW50ZXJ2YWwgZnJvbSAl\ncyB0byAlcyIsCiAgICAgICAgICAgIG9sZF91cGRhdGVfaW50ZXJ2YWwsCiAg\nICAgICAgICAgIGNvbnRyb2xsZXIudXBkYXRlX2ludGVydmFsLAogICAgICAg\nICkKCgpjbGFzcyBUZXNsYURhdGFVcGRhdGVDb29yZGluYXRvcihEYXRhVXBk\nYXRlQ29vcmRpbmF0b3IpOgogICAgIiIiQ2xhc3MgdG8gbWFuYWdlIGZldGNo\naW5nIFRlc2xhIGRhdGEuIiIiCgogICAgZGVmIF9faW5pdF9fKHNlbGYsIGhh\nc3MsICosIGNvbmZpZ19lbnRyeSwgY29udHJvbGxlcik6CiAgICAgICAgIiIi\nSW5pdGlhbGl6ZSBnbG9iYWwgVGVzbGEgZGF0YSB1cGRhdGVyLiIiIgogICAg\nICAgIHNlbGYuY29udHJvbGxlciA9IGNvbnRyb2xsZXIKICAgICAgICBzZWxm\nLmNvbmZpZ19lbnRyeSA9IGNvbmZpZ19lbnRyeQoKICAgICAgICB1cGRhdGVf\naW50ZXJ2YWwgPSB0aW1lZGVsdGEoc2Vjb25kcz1NSU5fU0NBTl9JTlRFUlZB\nTCkKCiAgICAgICAgc3VwZXIoKS5fX2luaXRfXygKICAgICAgICAgICAgaGFz\ncywKICAgICAgICAgICAgX0xPR0dFUiwKICAgICAgICAgICAgbmFtZT1ET01B\nSU4sCiAgICAgICAgICAgIHVwZGF0ZV9pbnRlcnZhbD11cGRhdGVfaW50ZXJ2\nYWwsCiAgICAgICAgKQoKICAgIGFzeW5jIGRlZiBfYXN5bmNfdXBkYXRlX2Rh\ndGEoc2VsZik6CiAgICAgICAgIiIiRmV0Y2ggZGF0YSBmcm9tIEFQSSBlbmRw\nb2ludC4iIiIKICAgICAgICBpZiBzZWxmLmNvbnRyb2xsZXIuaXNfdG9rZW5f\ncmVmcmVzaGVkKCk6CiAgICAgICAgICAgIHJlc3VsdCA9IHNlbGYuY29udHJv\nbGxlci5nZXRfdG9rZW5zKCkKICAgICAgICAgICAgcmVmcmVzaF90b2tlbiA9\nIHJlc3VsdFsicmVmcmVzaF90b2tlbiJdCiAgICAgICAgICAgIGFjY2Vzc190\nb2tlbiA9IHJlc3VsdFsiYWNjZXNzX3Rva2VuIl0KICAgICAgICAgICAgZXhw\naXJhdGlvbiA9IHJlc3VsdFsiZXhwaXJhdGlvbiJdCiAgICAgICAgICAgIF9h\nc3luY19zYXZlX3Rva2VucygKICAgICAgICAgICAgICAgIHNlbGYuaGFzcywg\nc2VsZi5jb25maWdfZW50cnksIGFjY2Vzc190b2tlbiwgcmVmcmVzaF90b2tl\nbiwgZXhwaXJhdGlvbgogICAgICAgICAgICApCiAgICAgICAgICAgIF9MT0dH\nRVIuZGVidWcoIlNhdmluZyBuZXcgdG9rZW5zIGluIGNvbmZpZ19lbnRyeSIp\nCgogICAgICAgIHRyeToKICAgICAgICAgICAgIyBOb3RlOiBhc3luY2lvLlRp\nbWVvdXRFcnJvciBhbmQgYWlvaHR0cC5DbGllbnRFcnJvciBhcmUgYWxyZWFk\neQogICAgICAgICAgICAjIGhhbmRsZWQgYnkgdGhlIGRhdGEgdXBkYXRlIGNv\nb3JkaW5hdG9yLgogICAgICAgICAgICBhc3luYyB3aXRoIGFzeW5jX3RpbWVv\ndXQudGltZW91dCgzMCk6CiAgICAgICAgICAgICAgICByZXR1cm4gYXdhaXQg\nc2VsZi5jb250cm9sbGVyLnVwZGF0ZSgpCiAgICAgICAgZXhjZXB0IEluY29t\ncGxldGVDcmVkZW50aWFsczoKICAgICAgICAgICAgYXdhaXQgc2VsZi5oYXNz\nLmNvbmZpZ19lbnRyaWVzLmFzeW5jX3JlbG9hZChzZWxmLmNvbmZpZ19lbnRy\neS5lbnRyeV9pZCkKICAgICAgICBleGNlcHQgVGVzbGFFeGNlcHRpb24gYXMg\nZXJyOgogICAgICAgICAgICByYWlzZSBVcGRhdGVGYWlsZWQoZiJFcnJvciBj\nb21tdW5pY2F0aW5nIHdpdGggQVBJOiB7ZXJyfSIpIGZyb20gZXJyCg==\n",
    "encoding": "base64",
    "_links": {
        "self": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/__init__.py?ref=tesla_oauth_callback",
        "git": "https://api.github.com/repos/alandtse/home-assistant/git/blobs/9e6db33d24ab50c1af1e1e2818580cc96069e076",
        "html": "https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
    },
}

MOCK_TRANSLATIONS_RESPONSE = [
    {
        "name": "__init__.py",
        "path": "homeassistant/components/tesla/__init__.py",
        "sha": "9e6db33d24ab50c1af1e1e2818580cc96069e076",
        "size": 9220,
        "url": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/__init__.py?ref=tesla_oauth_callback",
        "html_url": "https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
        "git_url": "https://api.github.com/repos/alandtse/home-assistant/git/blobs/9e6db33d24ab50c1af1e1e2818580cc96069e076",
        "download_url": "https://raw.githubusercontent.com/alandtse/home-assistant/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
        "type": "file",
        "_links": {
            "self": "https://api.github.com/repos/alandtse/home-assistant/contents/homeassistant/components/tesla/__init__.py?ref=tesla_oauth_callback",
            "git": "https://api.github.com/repos/alandtse/home-assistant/git/blobs/9e6db33d24ab50c1af1e1e2818580cc96069e076",
            "html": "https://github.com/alandtse/home-assistant/blob/tesla_oauth_callback/homeassistant/components/tesla/__init__.py",
        },
    },
]
